### PR TITLE
Improve CDN Whitelist handles.

### PR DESCRIPTION
**Pull request by jumpsmm7**
* Improvements for CDN Whitelist Regexp Detection. Consider Processing the ASN List separately without the "&". The multi- processing creates collisions resulting in some of the subnets sometimes not properly being processed. This might also result in additional hangs that wont be detected since the process runs in the background.

### CODE REVIEW

**Comment by Adamm00** [comment]
Going to need more info, what is your regex doing that the current isn't (missing entries, faster?). As for the removal of backgrounding, can you replicate a collision or entry being missed? I've always been genuinely curious but could never produce it.

**Comment by jumpsmm7** [comment]
@Adamm00 

The problem exists when running the command inside the while loop in the background. it causes gridlock with entries, thus the entry does not make it into the set. Basically on occasions you or other users have reported certain entries missing. Hypothetically, if the cpu is experiencing heavy load, then I imagine this gridlock would create a lot of missing entries. I can only speculate. 

The same symptoms can be reproduced if you print those same entries to a blank temporary file. You may occasionally notice a few lines will have colliding entries where both entries printed at the same time thus winding up printed on the same line. This is usually caused by a lot of busy resource competing operations going on at once which we might expect to happen if someone is running both diversion and skynet.

**Comment by jumpsmm7** [comment]
I added in the Microsoft endpoint list

**Comment by jumpsmm7** [comment]
But I will close this for now.

**Pull request closed without merging**
