### PR TITLE
Fix dependencies in 386.14

### PR DESCRIPTION
**Pull request by dave14305**
!!! This PR requires testing on 388 and 102 branches before deciding to merge or not. !!!

Remove support for John's fork and resolve conflicts between jQuery.noConflict() and latest ASUS JavaScript.

Re-order javascript loads to avoid unusual error in client_function.js toArray() call.

Also reverts Martinski's previous contribution which was a workaround for the jQuery issue.

### CODE REVIEW

**Comment by dave14305** [comment]
@Martinski4GitHub for review.

**Comment by dave14305** [comment]
Tested on 388.8 with RT-AX88U_PRO. Page loads cleanly and Update Stats button works fine.

**Comment by Adamm00** [comment]
Looks good on my GT-BE98 and GT-AXE16000. Appreciate both of your help on this one, webdev isn’t my strong suit.

**Comment by Martinski4GitHub** [comment]
> Tested on 388.8 with RT-AX88U_PRO. Page loads cleanly and Update Stats button works fine.
>
>
It's also working well on two routers: RT-AC86U (running **386.14**) & RT-AX86U (running **388.8**). No issues that I can see when loading the webpage.

**Pull request merged**
